---
apiVersion: v1
kind: Namespace
metadata:
  name: 5639d324-4f8d-466d-a482-a9e9bd830b85
  labels:
    name: 5639d324-4f8d-466d-a482-a9e9bd830b85
    # It bring the secret 'dacapod-argocd-config' using kubed
    decapod-argocd-config: enabled

